fix: cosign keyless

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -152,17 +152,29 @@ jobs:
             done
             [ $n -eq 3 ] && { echo "Failed to pull backend image after 3 attempts"; exit 1; }
 
+            # Clear and reinitialize TUF cache
+            rm -rf ~/.sigstore
+            n=0
+            until [ $n -ge 3 ]; do
+                cosign initialize && break
+                n=$((n+1))
+                echo "Retrying TUF initialization... $n"
+                sleep 5
+            done
+            [ $n -eq 3 ] && { echo "Failed to initialize TUF after 3 attempts"; exit 1; }
+
             # Verify the frontend image
             cosign verify \
-            --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}@refs/heads/${{ github.ref_name }}" \
-            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest || { echo "Frontend image signature verification failed"; exit 1; }
+              --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}@refs/heads/${{ github.ref_name }}" \
+              --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
+              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest || { echo "Frontend image signature verification failed"; exit 1; }
 
             # Verify the backend image
-            cosign verify
-            --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}@refs/heads/${{ github.ref_name }}"
-            --certificate-oidc-issuer "https://token.actions.githubusercontent.com"
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest || { echo "Backend image signature verification failed"; exit 1; }
+            cosign verify \
+              --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}@refs/heads/${{ github.ref_name }}" \
+              --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
+              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest || { echo "Backend image signature verification failed"; exit 1; }
+
 
             # Start services only if verification is successful
             docker compose up -d || { echo "Starting containers failed"; docker compose logs; exit 1; }
