test: registry issues

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -62,7 +62,7 @@ jobs:
   
       - name: Build and push Docker image for backend
         id: backend-build-and-push
-        uses: docker/build-push-action@v5.0.0
+        uses: docker/build-push-action@v6
         with:
           context: ./backend
           push: ${{ github.event_name != 'pull_request' }}
@@ -76,7 +76,7 @@ jobs:
       - name: Sign the published Docker images for frontend
         if: ${{ github.event_name != 'pull_request' }}
         env:
-          TAGS: ${{ steps.meta.outputs.tags }}
+          TAGS: ${{ steps.frontend-build-and-push.outputs.tags }}
           DIGEST: ${{ steps.frontend-build-and-push.outputs.digest }}
         run: |
           if [ -n "$DIGEST" ]; then
@@ -88,7 +88,7 @@ jobs:
       - name: Sign the published Docker images for backend
         if: ${{ github.event_name != 'pull_request' }}
         env:
-          TAGS: ${{ steps.meta.outputs.tags }}
+          TAGS: ${{ steps.backend-build-and-push.outputs.tags }}
           DIGEST: ${{ steps.backend-build-and-push.outputs.digest }}
         run: |
           if [ -n "$DIGEST" ]; then
@@ -106,9 +106,9 @@ jobs:
       - name: SSH and Deploy to Server
         uses: appleboy/ssh-action@master
         env: 
-            IMAGE_TAG: ${{ github.sha }}
-            REGISTRY: ghcr.io
-            IMAGE_NAME: ${{ github.repository }}
+          REGISTRY: ghcr.io
+          IMAGE_NAME: ${{ github.repository }}
+          IMAGE_TAG: ${{ github.sha }}
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
@@ -129,6 +129,7 @@ jobs:
             docker pull $REGISTRY/$IMAGE_NAME/backend:$IMAGE_TAG || docker pull $REGISTRY/$IMAGE_NAME/backend:latest
 
             # Start services
+            docker compose down || { echo "Stopping containers failed"; exit 1; }
             docker compose up -d || { echo "Starting containers failed"; exit 1; }
 
 
