test: deploy

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -111,11 +111,11 @@ jobs:
           script: |
 
             # Install cosign if not present
-            if ! command -v cosign &> /dev/null; then
-              echo "cosign not found, installing..."
-              sudo wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O /usr/local/bin/cosign
-              sudo chmod +x /usr/local/bin/cosign
-            fi
+            # if ! command -v cosign &> /dev/null; then
+            #   echo "cosign not found, installing..."
+            #   sudo wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O /usr/local/bin/cosign
+            #   sudo chmod +x /usr/local/bin/cosign
+            # fi
 
             # Log into GitHub Container Registry
             echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin || exit 1
